# Generated by Django 5.0.1 on 2024-10-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasestatistics',
            name='reported_at',
            field=models.DateTimeField(),
        ),
    ]
