# Generated by Django 5.0.1 on 2024-10-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_diseasestatistics_reported_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gene', models.CharField(max_length=255)),
                ('typical_region', models.CharField(max_length=255)),
            ],
        ),
    ]
