# Generated by Django 5.0.1 on 2024-10-06 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alert_alert_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='PestStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('reported_at', models.DateTimeField()),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pest')),
            ],
        ),
    ]
