# Generated by Django 5.0.1 on 2024-10-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_expertuser_managers_alter_regularuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
