# Generated by Django 5.0.1 on 2024-10-02 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_option_post_is_answered_post_is_question_quiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsolve',
            name='chosen_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.option'),
        ),
        migrations.AlterField(
            model_name='quizsolve',
            name='quiz_time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
