# Generated by Django 5.0.1 on 2024-10-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='explanation',
            field=models.TextField(blank=True),
        ),
    ]
